#!/usr/bin/env python
"""
Prepend directory and file names with parent directory name:

$ mv a_b/b_c a_b/a_b_c

(Notice that "b_c" does not get replaced by "a_b_b_c")

"""

import os
import argparse

parser = argparse.ArgumentParser(description="""
                    Rename files within a directory by directory name,
                    separated by an underscore.""",
                     formatter_class = lambda prog:
                     argparse.HelpFormatter(prog, max_help_position=40))
parser.add_argument("DIRECTORY",
                    help=('directory name'))
parser.add_argument("--debug",
                    help='show commands',
                    action='store_true')
args = parser.parse_args()
DIRECTORY = args.DIRECTORY
debug = args.debug

#-----------------------------------------------------------------------------
# Start walking through the directory tree from start_path:
#-----------------------------------------------------------------------------
DIRECTORY_split = DIRECTORY.split('_')[-1]
items = os.listdir(DIRECTORY)
for item in items:

    old = os.path.join(DIRECTORY, item)

    if item.startswith(DIRECTORY_split):
        item = item.replace(DIRECTORY_split,'')
    if item.startswith('_'):
        spc = ''
    else:
        spc = '_'
    new = os.path.join(DIRECTORY, DIRECTORY + spc + item)
    cmd = 'mv {0} {1}'.format(old, new)
    print(cmd)
    if not debug:
        os.system(cmd)
