#!/usr/bin/env python
"""
Substitute string in file names.

"""

import os
import argparse

parser = argparse.ArgumentParser(description="""
                    Find date strings and prepend formatted string to file names.""",
                     formatter_class = lambda prog:
                     argparse.HelpFormatter(prog, max_help_position=40))
parser.add_argument("DIRECTORY",
                    help=('Directory to search for files.'))
parser.add_argument("--debug",
                    help=("print, don't execute"),
                    action='store_true')
args = parser.parse_args()
DIRECTORY = args.DIRECTORY
debug = args.debug

MONs = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

#-----------------------------------------------------------------------------
# Start walking through the directory tree from start_path:
#-----------------------------------------------------------------------------
items = os.listdir(DIRECTORY)
for item in items:
    old = os.path.join(DIRECTORY, item)
    for iMON, MON in enumerate(MONs):
        if MON in item:
            if iMON < 10:
                iMON = '0' + str(iMON)
            else:
                iMON = str(iMON)

            i = item.find(MON)

            dy = item[i-2:i]
            year = item[i+3:i+7]
            if year.isdigit():
                yr = year
            else:
                yr = '20' + item[i+3:i+5]
            DATE = '-'.join([yr, iMON, dy])

            new = os.path.join(DIRECTORY, DATE + '_' + item)
            cmd = 'mv {0} {1}'.format(old, new)
            print(cmd)
            if not debug:
                os.system(cmd)

