#!/usr/bin/env python
"""
Substitute string in file names.

"""

import os
import argparse

parser = argparse.ArgumentParser(description="""
                    Find date strings and prepend formatted string to file names.""",
                     formatter_class = lambda prog:
                     argparse.HelpFormatter(prog, max_help_position=40))
parser.add_argument("DIRECTORY",
                    help=('Directory to search for files.'))
parser.add_argument("--debug",
                    help=("print, don't execute"),
                    action='store_true')
args = parser.parse_args()
DIRECTORY = args.DIRECTORY
debug = args.debug

#-----------------------------------------------------------------------------
# Start walking through the directory tree from start_path:
#-----------------------------------------------------------------------------
items = os.listdir(DIRECTORY)
for item in items:
    old = os.path.join(DIRECTORY, item)

    dy = item[6:8]
    mon = item[8:10]
    yr = item[10:12]

    DATE = '-'.join(['20'+yr, mon, dy])

    new = os.path.join(DIRECTORY, DATE + '_' + item)
    cmd = 'mv {0} {1}'.format(old, new)
    print(cmd)
    if not debug:
        os.system(cmd)

