#!/usr/bin/env python
"""
Substitute string in file names.

"""

import os
import argparse

parser = argparse.ArgumentParser(description="""
                    Substitute string in file names.""",
                     formatter_class = lambda prog:
                     argparse.HelpFormatter(prog, max_help_position=40))
parser.add_argument("DIRECTORY",
                    help=('Directory to search for files.'))
parser.add_argument("-i", "--input",
                    help=("input (search) string"),
                    metavar='STR')
parser.add_argument("-o", "--output",
                    help=("output string"),
                    metavar='STR')
parser.add_argument("--debug",
                    help=("print, don't execute"),
                    action='store_true')
args = parser.parse_args()
DIRECTORY = args.DIRECTORY
instr = args.input
outstr = args.output
debug = args.debug

#-----------------------------------------------------------------------------
# Start walking through the directory tree from start_path:
#-----------------------------------------------------------------------------
items = os.listdir(DIRECTORY)
for item in items:

    if instr in item:

        old = os.path.join(DIRECTORY, item)
        new = os.path.join(DIRECTORY, item.replace(instr, outstr))

        cmd = 'mv {0} {1}'.format(old, new)
        print(cmd)
        if not debug:
            os.system(cmd)
