#!/usr/bin/env python
"""
tar.gz files in a directory.

"""

import os
import argparse

parser = argparse.ArgumentParser(description="""
                    Compress files in a directory.""",
                     formatter_class = lambda prog:
                     argparse.HelpFormatter(prog, max_help_position=40))
parser.add_argument("DIRECTORY",
                    help=('Directory to search for files.'))
args = parser.parse_args()
DIRECTORY = args.DIRECTORY

#-----------------------------------------------------------------------------
# Start walking through the directory tree from start_path:
#-----------------------------------------------------------------------------
items = os.listdir(DIRECTORY)
for item in items:

        filename = os.path.join(DIRECTORY, item)

        cmd = 'tar cvfz {0}.tar.gz {0}'.format(filename)
        print(cmd)
        os.system(cmd)
